const FETCH_REQUEST = 'users/FETCH_REQUEST';
const FETCH_SUCCESS = 'users/FETCH_SUCCESS';
const FETCH_ERROR = 'users/FETCH_ERROR';

const FILTERED_NAME = 'filter/FILTERED_NAME';
const FILTERED_JOB = 'filter/FILTERED_JOB';
const FILTERED_EMAIL = 'filter/FILTERED_EMAIL';
const FILTERED_PHONE = 'filter/FILTERED_PHONE';

export default {
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
  FILTERED_NAME,
  FILTERED_JOB,
  FILTERED_EMAIL,
  FILTERED_PHONE,
};
